### ISSUE TITLE
action is not removing all untagged images at one

### ISSUE THREAD

**Issue by lukaszgoworko** [dylanratcliffe/delete-untagged-containers#1]
This is the job I have created:

```yaml
name: Delete Untagged Images
on:
  workflow_dispatch:
    inputs:
      image_name:
        description: 'The name of the Docker image to delete untagged versions for'
        required: true

jobs:
  remove-untagged-images:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Untagged Images
        uses: dylanratcliffe/delete-untagged-containers@v1.0.0
        with:
          package_name: ${{ github.event.inputs.image_name }}
          token: ${{ secrets.MACHINE_USER_VILO_PAT }}
```

I have about 100 images in my project, witch are not tagged.
this is the outcome of the Job
```
Run dylanratcliffe/delete-untagged-containers@v1.0.0
  with:
    package_name: product-service/nginx
    token: ***
Detected org/user type: org
Checking if package product-service/nginx exists in org vilo-cloud
Found package id: 765987
Getting 215 package versions
Deleting untagged version: sha256:eacf81b51b08b1e124866bc06dbf5da2328c654ae6c0a697e15456213607ffb4
Status: 204
Deleting untagged version: sha256:85c2a3e8e83102e75740b9c9dcb7ea19435c76398ed2106ae97b4c168034e488
Status: 204
Deleting untagged version: sha256:7b4a15b94c42dfbcc31da87036062c286d31f2585c478e40bef0970475eb1935
Status: 204
``` 
When I rerun the job some more are removed, but again not all of them. At some point no other untagged images are deleted.

Information about the images
They are all older then "3 month ago"
